package org.ual.hmis.gomezMontalban;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CambiodecontraseadeusuariologueadoCasoincorrectoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe"); 
	System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cambiodecontraseadeusuariologueadoCasoincorrecto() {
    // Test name: Cambio de contraseña de usuario logueado (Caso incorrecto)
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:1337/");
    // 2 | setWindowSize | 1280x726 | 
    driver.manage().window().setSize(new Dimension(1280, 726));
    // 3 | click | linkText=Log in | 
    driver.findElement(By.linkText("Log in")).click();
    // 4 | type | css=.form-group:nth-child(2) > .form-control | biRjem-hazvis-vagma1
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("biRjem-hazvis-vagma1");
    // 5 | type | css=.form-group:nth-child(1) > .form-control | guillermosysti@gmail.com
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).sendKeys("guillermosysti@gmail.com");
    // 6 | click | css=.ajax-button | 
    driver.findElement(By.cssSelector(".ajax-button")).click();
    // 7 | click | id=header-account-menu-link | 
    driver.findElement(By.id("header-account-menu-link")).click();
    // 8 | click | linkText=Settings | 
    driver.findElement(By.linkText("Settings")).click();
    // 9 | click | linkText=Change password | 
    driver.findElement(By.linkText("Change password")).click();
    // 10 | type | id=password | 1234
    driver.findElement(By.id("password")).sendKeys("1234");
    // 11 | click | id=confirm-password | 
    driver.findElement(By.id("confirm-password")).click();
    // 12 | type | id=confirm-password | 123
    driver.findElement(By.id("confirm-password")).sendKeys("123");
    // 13 | click | css=.button-text | 
    driver.findElement(By.cssSelector(".button-text")).click();
    // 14 | assertText | xpath=//div[@id='edit-password']/div[2]/form/div/div[2]/div/div | Your new password and confirmation do not match.
    assertThat(driver.findElement(By.xpath("//div[@id=\'edit-password\']/div[2]/form/div/div[2]/div/div")).getText(), is("Your new password and confirmation do not match."));
  }
}
